import AppKit
@preconcurrency import SwiftTerm

/// Thin subclass that intercepts outgoing key data for broadcast mode
/// while still calling super to let the PTY receive input normally.
final class InterceptingTerminalView: LocalProcessTerminalView {
    var onSendData: (@Sendable (ArraySlice<UInt8>) -> Void)?
    /// Set to true while programmatically sending broadcast data so we don't
    /// re-trigger onSendData and cause an infinite broadcast loop.
    var suppressBroadcast = false

    /// Cached before background dispatch — startProcess calls getWindowSize() which
    /// reads self.frame; NSView.frame must only be accessed on the main thread.
    nonisolated(unsafe) var cachedWindowSize: winsize?

    override func getWindowSize() -> winsize {
        cachedWindowSize ?? super.getWindowSize()
    }

    /// Intercept outgoing data for broadcast. `send(source:data:)` is called for both
    /// user keystrokes and SwiftTerm's internal terminal protocol responses (DA1, DA2,
    /// CPR, etc.). Filter out protocol responses by their DEC private prefix (ESC [ ?
    /// or ESC [ >) — these sequences are exclusively generated by the terminal emulator
    /// in response to application queries and are never produced by user keyboard input.
    override func send(source: TerminalView, data: ArraySlice<UInt8>) {
        super.send(source: source, data: data)   // PTY receives input as normal
        guard !suppressBroadcast else { return }
        // ESC [ ? and ESC [ > are DEC private mode prefixes used only in terminal
        // protocol responses (DA1/DA2, XTWINOPS, etc.), never in user keystrokes.
        if data.count >= 3,
           data[data.startIndex] == 0x1B,
           data[data.startIndex + 1] == 0x5B,
           data[data.startIndex + 2] == 0x3F || data[data.startIndex + 2] == 0x3E {
            return
        }
        onSendData?(data)
    }

    /// SwiftTerm's default linefeed clears selection on every output line, making it
    /// impossible to select text while the terminal is streaming output. Don't propagate —
    /// selection is cleared appropriately by keyDown and mouseDown instead.
    override func linefeed(source: Terminal) {}

}

private let titleBarHeight: CGFloat = 28
private let minSize = CGSize(width: 200, height: 120)

/// A free-floating terminal window in world space.
/// Contains a title bar, a SwiftTerm LocalProcessTerminalView, and 8 resize handles.
final class TerminalWindowView: NSView {

    // MARK: - Identity

    let id = UUID()
    let shell: String
    var currentCwd: String
    var currentTitle: String = "Terminal"

    /// True once the shell has emitted its first title sequence — used to gate
    /// broadcast input so fresh terminals aren't sent keystrokes before the
    /// shell prompt is ready.
    private(set) var shellReady = false

    // MARK: - Callbacks

    var onClose: (() -> Void)?
    var onMoved: (() -> Void)?
    /// Fired when a drag or resize gesture completes; carries (fromFrame, toFrame).
    var onMoveEnded: ((CGRect, CGRect) -> Void)?
    /// Called during drag with the proposed frame; returns the (possibly snapped) frame.
    var snapFrame: ((CGRect, ResizeHandleView.Edge?) -> CGRect)?
    var clearSnapGuides: (() -> Void)?
    /// Raw input bytes to broadcast (only fired if broadcast mode is active upstream).
    var onBroadcastKey: ((Data) -> Void)?
    /// Fired each drag tick with the world-space delta; used for group-move.
    var onDragDelta: ((CGFloat, CGFloat) -> Void)?
    /// Fired when a title-bar drag gesture begins; used for group-move undo capture.
    var onDragBegan: (() -> Void)?

    /// Active theme — applied 0.8 s after process start (after shell init sequences).
    var theme: Theme = .dark

    // MARK: - Subviews

    private let titleBar = TitleBarView()
    // nonisolated(unsafe): startProcess is dispatched to a background queue to keep
    // forkpty() off the main thread. SwiftTerm dispatches all post-fork UI callbacks
    // back to the main thread internally.
    private nonisolated(unsafe) var termView: InterceptingTerminalView!
    private var frameBeforeDrag: CGRect = .zero
    private nonisolated(unsafe) var kittyArrowMonitor: Any?
    private nonisolated(unsafe) var flagsMonitor: Any?
    private var linkCursorPushed = false

    // MARK: - Canvas reference (for zoom-corrected drag)

    weak var canvasView: CanvasView?

    /// Plain-text scrollback to re-display on launch (dimmed, before shell prompt).
    var restoredScrollback: String?

    // MARK: - Init

    init(frame: CGRect, shell: String, cwd: String?) {
        self.shell = shell
        self.currentCwd = cwd ?? FileManager.default.homeDirectoryForCurrentUser.path
        super.init(frame: frame)
        setup()
    }

    required init?(coder: NSCoder) { fatalError() }

    deinit {
        if let monitor = kittyArrowMonitor { NSEvent.removeMonitor(monitor) }
        if let monitor = flagsMonitor { NSEvent.removeMonitor(monitor) }
    }

    // MARK: - Focus state

    var isActive: Bool = false {
        didSet { updateBorder() }
    }
    var isBroadcast: Bool = false

    private func updateBorder() {
        let dark = theme.terminalBackground.isPerceivedDark
        layer?.borderColor = isActive
            ? (dark ? NSColor(white: 0.75, alpha: 1) : NSColor(white: 0.2, alpha: 1)).cgColor
            : (dark ? NSColor(white: 0.25, alpha: 1) : NSColor(white: 0.72, alpha: 1)).cgColor
        layer?.borderWidth = isActive ? 2 : 1
    }

    private func setup() {
        wantsLayer = true
        layer?.cornerRadius = 8
        layer?.masksToBounds = true
        layer?.borderColor = NSColor(white: 0.25, alpha: 1).cgColor
        layer?.borderWidth = 1
        layer?.backgroundColor = Theme.dark.terminalBackground.cgColor

        setupTitleBar()
        setupTerminal()
        setupResizeHandles()
    }

    // MARK: - Title bar

    private func setupTitleBar() {
        titleBar.translatesAutoresizingMaskIntoConstraints = false
        addSubview(titleBar)
        NSLayoutConstraint.activate([
            titleBar.leadingAnchor.constraint(equalTo: leadingAnchor),
            titleBar.trailingAnchor.constraint(equalTo: trailingAnchor),
            titleBar.topAnchor.constraint(equalTo: topAnchor),
            titleBar.heightAnchor.constraint(equalToConstant: titleBarHeight),
        ])

        titleBar.onClose = { [weak self] in self?.onClose?() }

        titleBar.onDragBegan = { [weak self] in
            guard let self else { return }
            frameBeforeDrag = frame
            onDragBegan?()
        }

        titleBar.onDrag = { [weak self] screenDX, screenDY in
            guard let self, let cv = self.canvasView else { return }
            let zoom = cv.currentZoom
            let proposed = CGRect(x: self.frame.origin.x + screenDX / zoom,
                                  y: self.frame.origin.y - screenDY / zoom,
                                  width: self.frame.width, height: self.frame.height)
            let oldOrigin = self.frame.origin
            self.frame = self.snapFrame?(proposed, nil) ?? proposed
            self.onDragDelta?(self.frame.origin.x - oldOrigin.x, self.frame.origin.y - oldOrigin.y)
            self.onMoved?()
        }

        titleBar.onDragEnded = { [weak self] in
            guard let self else { return }
            clearSnapGuides?()
            guard frame != frameBeforeDrag else { return }
            onMoveEnded?(frameBeforeDrag, frame)
        }
    }

    // MARK: - Terminal

    private func setupTerminal() {
        // Frame will be updated in layoutSubviews
        let termFrame = CGRect(x: 0, y: titleBarHeight,
                               width: frame.width, height: frame.height - titleBarHeight)
        termView = InterceptingTerminalView(frame: termFrame)
        termView.translatesAutoresizingMaskIntoConstraints = false
        termView.processDelegate = self
        termView.onSendData = { @Sendable [weak self] data in
            let bytes = Data(data)
            Task { @MainActor [weak self] in
                self?.onBroadcastKey?(bytes)
            }
        }
        termView.nativeForegroundColor = theme.terminalForeground
        termView.nativeBackgroundColor = theme.terminalBackground
        addSubview(termView)

        let p: CGFloat = 8
        NSLayoutConstraint.activate([
            termView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: p),
            termView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -p),
            termView.topAnchor.constraint(equalTo: topAnchor, constant: titleBarHeight),
            termView.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -p),
        ])

        // Force dark appearance so the legacy scroller track renders dark
        // regardless of the system-wide appearance setting.
        termView.appearance = NSAppearance(named: .darkAqua)

        // Fix SwiftTerm/macOS interaction: macOS always sets .numericPad on cursor arrow
        // keys. In kitty keyboard mode SwiftTerm uses that flag to distinguish keypad
        // arrows from cursor arrows — causing cursor arrows to be sent as CSI 57419u/57420u
        // (keypad) instead of CSI A/B (cursor). Strip .numericPad so SwiftTerm takes the
        // cursor-arrow path. We can't override keyDown (not open), so we use a local monitor.
        //
        // TODO(2026-04-08): Re-evaluate whether this is still needed. Introduced as a
        // workaround for a Claude Code v2.1.83 regression ("Fixed mouse tracking escape
        // sequences leaking to shell prompt after exit") that caused kitty keyboard mode
        // to be pushed to terminals not in the kitty allow-list. If CC has been fixed,
        // remove this monitor.
        kittyArrowMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self,
                  self.window?.firstResponder === self.termView else { return event }

            // Shift+Enter: send \x1b[13;2u (kitty keyboard protocol Shift+Enter).
            // Claude Code recognises this sequence natively (same as iTerm2/Ghostty).
            // Must intercept unconditionally — SwiftTerm drops the Shift modifier when
            // routing Return through doCommand(insertNewline:) regardless of kitty mode.
            if event.keyCode == 36, event.modifierFlags.contains(.shift) {
                self.termView.send(data: [0x1B, 0x5B, 0x31, 0x33, 0x3B, 0x32, 0x75][...])
                return nil
            }

            // numericPad fix: only applies when kitty keyboard mode is active.
            guard !self.termView.terminal.keyboardEnhancementFlags.isEmpty,
                  event.modifierFlags.contains(.numericPad),
                  let cgOrig = event.cgEvent,
                  let cgCopy = cgOrig.copy() else { return event }
            cgCopy.flags = cgCopy.flags.subtracting(.maskNumericPad)
            return NSEvent(cgEvent: cgCopy) ?? event
        }

        // Show a pointing-hand cursor when Cmd is held — matches SwiftTerm's link-underline
        // behaviour. cursorUpdate(with:) is public (not open) in SwiftTerm so we can't
        // override it; use a flagsChanged monitor instead.
        flagsMonitor = NSEvent.addLocalMonitorForEvents(matching: .flagsChanged) { [weak self] event in
            guard let self else { return event }
            let cmdHeld = event.modifierFlags.contains(.command)
            let overTerminal = self.window?.firstResponder === self.termView
            if cmdHeld && overTerminal && !self.linkCursorPushed {
                NSCursor.pointingHand.push()
                self.linkCursorPushed = true
            } else if (!cmdHeld || !overTerminal) && self.linkCursorPushed {
                NSCursor.pop()
                self.linkCursorPushed = false
            }
            return event
        }

        startProcess()
    }

    /// Extract up to `maxLines` of scrollback + visible screen content as plain text.
    func extractScrollbackText(maxLines: Int = 300) -> String {
        let t = termView.terminal!
        var lines: [String] = []

        // Walk backwards through scrollback (negative row indices into getScrollInvariantLine)
        var row = -1
        while lines.count < maxLines {
            guard let line = t.getScrollInvariantLine(row: row) else { break }
            lines.insert(line.translateToString(trimRight: false, characterProvider: { let c = $0.getCharacter(); return c == "\0" ? " " : c }), at: 0)
            row -= 1
        }

        // Visible screen lines
        for r in 0..<t.rows {
            if let line = t.getScrollInvariantLine(row: r) {
                lines.append(line.translateToString(trimRight: false, characterProvider: { let c = $0.getCharacter(); return c == "\0" ? " " : c }))
            }
        }

        // Drop trailing blank lines
        while lines.last?.isEmpty == true { lines.removeLast() }
        return lines.joined(separator: "\r\n")
    }

    /// Forward a find-panel action to the SwiftTerm terminal view.
    /// Pass a nil sender to default to "show find panel".
    func performFind(_ sender: Any?) {
        if let item = sender as? NSMenuItem {
            termView.performFindPanelAction(item)
        } else {
            let item = NSMenuItem(title: "", action: nil, keyEquivalent: "")
            item.tag = Int(NSFindPanelAction.showFindPanel.rawValue)
            termView.performFindPanelAction(item)
        }
    }

    /// Clear scrollback and screen (Cmd+K behaviour). Feeds ESC sequences directly
    /// to the terminal display — does not send anything to the PTY.
    func clearScrollback() {
        // ESC[H  = cursor home
        // ESC[2J = erase screen
        // ESC[3J = erase saved lines (scrollback)
        termView.feed(byteArray: [0x1B, 0x5B, 0x48,
                                  0x1B, 0x5B, 0x32, 0x4A,
                                  0x1B, 0x5B, 0x33, 0x4A])
    }

    private func startProcess() {
        let settings = TerminalSettings.shared
        applyTerminalSettings(settings)

        var env = ProcessInfo.processInfo.environment
        env["TERM"] = "xterm-256color"
        env["COLORTERM"] = "truecolor"

        var isDir: ObjCBool = false
        let cwdExists = FileManager.default.fileExists(atPath: currentCwd, isDirectory: &isDir) && isDir.boolValue
        let cwd = cwdExists ? currentCwd : FileManager.default.homeDirectoryForCurrentUser.path

        let execName = "-" + (shell as NSString).lastPathComponent
        let envList  = env.map { "\($0.key)=\($0.value)" }
        let shellPath = shell
        let scrollbackLines = settings.scrollbackLines
        let cursorStyle = settings.swiftTermCursorStyle

        // Cache window size before background dispatch — startProcess calls getWindowSize()
        // which reads self.frame; that must happen on the main thread.
        termView!.cachedWindowSize = termView!.getWindowSize()

        // Run forkpty on a background thread so the ~2 s atfork-handler cost
        // (libBacktraceRecording) doesn't block the main thread and cause a beachball.
        // SwiftTerm annotates startProcess as @MainActor but the underlying forkpty
        // call is thread-safe; the annotation is overly conservative. Calling from a
        // background thread here is intentional and safe.
        DispatchQueue.global(qos: .userInitiated).async { [termView] in
            termView!.startProcess(
                executable: shellPath,
                args: [],
                environment: envList,
                execName: execName,
                currentDirectory: cwd
            )
            DispatchQueue.main.async {
                // Clear the cached size now that the process is running.
                // sizeChanged() calls getWindowSize() to build the TIOCSWINSZ winsize;
                // from this point it must read the live frame, not the startup snapshot.
                termView!.cachedWindowSize = nil
                termView!.changeScrollback(scrollbackLines)
                termView!.getTerminal().setCursorStyle(cursorStyle)
            }
        }

        // Apply theme and optionally restore scrollback after shell init sequences have run.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { [weak self] in
            guard let self else { return }
            self.applyTheme(self.theme)
            if let text = self.restoredScrollback, !text.isEmpty {
                self.restoredScrollback = nil
                // Strip all ANSI/OSC escape sequences from the persisted scrollback
                // before re-feeding it. Without this, a tampered workspace.json could
                // inject OSC sequences (e.g. OSC 8 hyperlinks, OSC 1337 file transfers,
                // title-setting sequences) into the running terminal.
                // NUL bytes (U+0000) arise from terminal cells that were never explicitly
                // written (cursor-positioned TUI layouts). Replace them with spaces so they
                // render correctly when re-fed to the terminal emulator.
                let safe = TerminalWindowView.stripEscapeSequences(text)
                    .replacingOccurrences(of: "\u{0000}", with: " ")
                // Dim color + italic, then show saved content, then reset
                let dimmed = "\u{1B}[2;3m" + safe + "\u{1B}[0m\r\n"
                self.termView.feed(text: dimmed)
            }
        }
    }

    /// Remove ANSI CSI sequences (`ESC [ … m/A/B/…`), OSC sequences
    /// (`ESC ] … BEL/ST`), and bare `ESC X` two-character sequences from `text`.
    /// Used to sanitise persisted scrollback before re-feeding it to the terminal.
    static func stripEscapeSequences(_ text: String) -> String {
        var result = ""
        result.reserveCapacity(text.count)
        var iter = text.unicodeScalars.makeIterator()
        while let ch = iter.next() {
            guard ch == "\u{1B}" else { result.unicodeScalars.append(ch); continue }
            // Peek at the next character to classify the sequence type.
            guard let next = iter.next() else { break }
            switch next {
            case "[":
                // CSI: consume until a byte in 0x40–0x7E (the final byte)
                while let c = iter.next() {
                    if c.value >= 0x40 && c.value <= 0x7E { break }
                }
            case "]",   // OSC  (Operating System Command)
                 "P",   // DCS  (Device Control String)
                 "X",   // SOS  (Start of String)
                 "^",   // PM   (Privacy Message)
                 "_":   // APC  (Application Program Command)
                // All ST-terminated sequences: consume until BEL (0x07) or ST (ESC \)
                var prev: Unicode.Scalar = "\u{00}"
                while let c = iter.next() {
                    if c == "\u{07}" { break }
                    if prev == "\u{1B}" && c == "\\" { break }
                    prev = c
                }
            default:
                // Two-character escape sequence — already consumed `next`; discard it.
                break
            }
        }
        return result
    }

    func applyTerminalSettings(_ settings: TerminalSettings) {
        termView.optionAsMetaKey        = settings.optionAsMetaKey
        termView.backspaceSendsControlH = settings.backspaceSendsControlH
        termView.allowMouseReporting    = settings.allowMouseReporting
        termView.useBrightColors        = settings.useBrightColors
        termView.changeScrollback(settings.scrollbackLines)
        termView.getTerminal().setCursorStyle(settings.swiftTermCursorStyle)
    }

    func applyTheme(_ theme: Theme) {
        self.theme = theme
        termView.nativeForegroundColor = theme.terminalForeground
        termView.nativeBackgroundColor = theme.terminalBackground
        termView.font = theme.terminalFont
        termView.feed(text: theme.oscSequences)
        layer?.backgroundColor = theme.terminalBackground.cgColor
        titleBar.applyTheme(background: theme.terminalBackground, foreground: theme.terminalForeground)
        updateBorder()
    }

    private func syncTitleBarColor() {
        if isBroadcast {
            titleBar.layer?.backgroundColor = NSColor(red: 0.15, green: 0.3, blue: 0.15, alpha: 1).cgColor
        } else {
            titleBar.applyTheme(background: theme.terminalBackground, foreground: theme.terminalForeground)
        }
    }

    // MARK: - Resize handles

    private func setupResizeHandles() {
        for edge in ResizeHandleView.Edge.allCases {
            let h = ResizeHandleView(edge: edge)
            h.translatesAutoresizingMaskIntoConstraints = false
            addSubview(h)
            h.installConstraints(in: self)
            h.onResizeBegan = { [weak self] in
                guard let self else { return }
                frameBeforeDrag = frame
            }
            h.onResize = { [weak self] dx, dy in
                self?.handleResize(edge: edge, screenDX: dx, screenDY: dy)
            }
            h.onResizeEnded = { [weak self] in
                guard let self else { return }
                clearSnapGuides?()
                guard frame != frameBeforeDrag else { return }
                onMoveEnded?(frameBeforeDrag, frame)
            }
        }
    }

    private func handleResize(edge: ResizeHandleView.Edge, screenDX: CGFloat, screenDY: CGFloat) {
        guard let cv = canvasView else { return }
        let zoom = cv.currentZoom
        let dx = screenDX / zoom
        // screenDY is window-space y-up; world space is y-down, so negate
        let dy = -screenDY / zoom

        var r = frame
        switch edge {
        case .topLeft:
            r.origin.x += dx; r.size.width -= dx
            r.origin.y += dy; r.size.height -= dy
        case .top:
            r.origin.y += dy; r.size.height -= dy
        case .topRight:
            r.size.width += dx
            r.origin.y += dy; r.size.height -= dy
        case .left:
            r.origin.x += dx; r.size.width -= dx
        case .right:
            r.size.width += dx
        case .bottomLeft:
            r.origin.x += dx; r.size.width -= dx
            r.size.height += dy
        case .bottom:
            r.size.height += dy
        case .bottomRight:
            r.size.width += dx
            r.size.height += dy
        }

        r.size.width  = max(r.size.width,  minSize.width)
        r.size.height = max(r.size.height, minSize.height)

        // Apply edge-aware snapping: call snapFrame to find alignment deltas, then
        // apply each delta to the dimension that's actually moving for this edge.
        if let snap = snapFrame {
            let snapped = snap(r, edge)
            let sdx = snapped.origin.x - r.origin.x
            let sdy = snapped.origin.y - r.origin.y

            let dragsRight  = edge == .right  || edge == .topRight    || edge == .bottomRight
            let dragsLeft   = edge == .left   || edge == .topLeft     || edge == .bottomLeft
            let dragsBottom = edge == .bottom || edge == .bottomLeft  || edge == .bottomRight
            let dragsTop    = edge == .top    || edge == .topLeft     || edge == .topRight

            if dragsRight       { r.size.width  += sdx }
            else if dragsLeft   { r.origin.x    += sdx; r.size.width  -= sdx }
            if dragsBottom      { r.size.height += sdy }
            else if dragsTop    { r.origin.y    += sdy; r.size.height -= sdy }

            r.size.width  = max(r.size.width,  minSize.width)
            r.size.height = max(r.size.height, minSize.height)
        }

        frame = r
        onMoved?()
    }

    // MARK: - Focus

    func focusTerminal() {
        window?.makeFirstResponder(termView)
    }

    // MARK: - Input broadcasting

    func sendInput(_ data: Data) {
        let bytes = [UInt8](data)
        termView.suppressBroadcast = true
        termView.send(data: bytes[...])
        termView.suppressBroadcast = false
    }

    // MARK: - Visual state

    func setBroadcastHighlight(_ on: Bool) {
        isBroadcast = on
        syncTitleBarColor()
    }

    func terminate() {
        // SwiftTerm tears down the PTY when the view is deallocated,
        // but we can signal the process to exit cleanly.
        termView.send(data: [0x04][...])  // Ctrl-D / EOF
    }
}

// MARK: - LocalProcessTerminalViewDelegate

extension TerminalWindowView: LocalProcessTerminalViewDelegate {
    nonisolated func sizeChanged(source: LocalProcessTerminalView, newCols: Int, newRows: Int) {
        // SIGWINCH is sent automatically by SwiftTerm; nothing extra needed here
    }

    nonisolated func setTerminalTitle(source: LocalProcessTerminalView, title: String) {
        Task { @MainActor [weak self] in
            self?.shellReady = true
            self?.currentTitle = title
            self?.titleBar.titleLabel.stringValue = title
            self?.syncTitleBarColor()
        }
    }

    nonisolated func hostCurrentDirectoryUpdate(source: TerminalView, directory: String?) {
        guard let dir = directory else { return }
        // SwiftTerm passes a file:// URL; extract the plain POSIX path.
        let path = URL(string: dir)?.path ?? dir
        Task { @MainActor [weak self] in
            self?.currentCwd = path
        }
    }

    nonisolated func processTerminated(source: TerminalView, exitCode: Int32?) {
        Task { @MainActor [weak self] in
            self?.onClose?()
        }
    }
}


