import AppKit
@preconcurrency import SwiftTerm

/// Thin subclass that intercepts outgoing key data for broadcast mode
/// while still calling super to let the PTY receive input normally.
final class InterceptingTerminalView: LocalProcessTerminalView {
    var onSendData: (@Sendable (ArraySlice<UInt8>) -> Void)?
    /// Set to true while programmatically sending broadcast data so we don't
    /// re-trigger onSendData and cause an infinite broadcast loop.
    var suppressBroadcast = false

    /// Cached before background dispatch — startProcess calls getWindowSize() which
    /// reads self.frame; NSView.frame must only be accessed on the main thread.
    nonisolated(unsafe) var cachedWindowSize: winsize?

    override func getWindowSize() -> winsize {
        cachedWindowSize ?? super.getWindowSize()
    }

    /// Intercept outgoing data for broadcast. `send(source:data:)` is called for both
    /// user keystrokes and SwiftTerm's internal terminal protocol responses (DA1, DA2,
    /// CPR, etc.). Filter out protocol responses by their DEC private prefix (ESC [ ?
    /// or ESC [ >) — these sequences are exclusively generated by the terminal emulator
    /// in response to application queries and are never produced by user keyboard input.
    override func send(source: TerminalView, data: ArraySlice<UInt8>) {
        super.send(source: source, data: data)   // PTY receives input as normal
        guard !suppressBroadcast else { return }
        // ESC [ ? and ESC [ > are DEC private mode prefixes used only in terminal
        // protocol responses (DA1/DA2, XTWINOPS, etc.), never in user keystrokes.
        if data.count >= 3,
           data[data.startIndex] == 0x1B,
           data[data.startIndex + 1] == 0x5B,
           data[data.startIndex + 2] == 0x3F || data[data.startIndex + 2] == 0x3E {
            return
        }
        onSendData?(data)
    }

    /// SwiftTerm's default linefeed clears selection on every output line, making it
    /// impossible to select text while the terminal is streaming output. Don't propagate —
    /// selection is cleared appropriately by keyDown and mouseDown instead.
    override func linefeed(source: Terminal) {}

    /// SwiftTerm's feedPrepare() clears selection when allowMouseReporting is true,
    /// which kills any active selection every time terminal data arrives. Temporarily
    /// disable allowMouseReporting around the feed so the selection persists — the
    /// same approach iTerm2 and Terminal.app use to keep selection alive during output.
    override func dataReceived(slice: ArraySlice<UInt8>) {
        let wasReporting = allowMouseReporting
        if wasReporting && selectionActive {
            allowMouseReporting = false
        }
        super.dataReceived(slice: slice)
        if wasReporting && !allowMouseReporting {
            allowMouseReporting = wasReporting
        }
    }

    var onBell: (() -> Void)?

    /// Trim trailing whitespace from each copied line. SwiftTerm includes empty
    /// cells (padded with spaces) past the last printed character on each row,
    /// which is almost never what the user wants on the clipboard.
    override func copy(_ sender: Any) {
        let raw = getSelection() ?? ""
        guard !raw.isEmpty else {
            super.copy(sender)
            return
        }
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(Self.sanitizeForClipboard(Self.trimTrailingSpacesPerLine(raw)),
                     forType: .string)
    }

    /// Strip Unicode characters that allow malicious PTY output to display one thing
    /// and paste another: bidi overrides (U+202A–U+202E, U+2066–U+2069), zero-width
    /// chars (U+200B–U+200D, U+2060, U+FEFF), and the line/paragraph separators
    /// (U+2028/U+2029) that some shells treat as newlines. Defends against the
    /// "innocuous-looking command pastes as `rm -rf …`" class of attack
    /// (cf. iTerm2 2017, CVE-2017-2671).
    static func sanitizeForClipboard(_ text: String) -> String {
        var out = String.UnicodeScalarView()
        out.reserveCapacity(text.unicodeScalars.count)
        for s in text.unicodeScalars {
            switch s.value {
            case 0x202A...0x202E, 0x2066...0x2069,            // bidi overrides / isolates
                 0x200B...0x200D, 0x2060, 0xFEFF:             // zero-width
                continue
            case 0x2028, 0x2029:                              // line/paragraph separator
                out.append("\n")
            default:
                out.append(s)
            }
        }
        return String(out)
    }

    static func trimTrailingSpacesPerLine(_ text: String) -> String {
        // Operate on UnicodeScalars: in the Character view, "\r\n" is a single
        // grapheme cluster, so splitting on the Character "\n" misses CRLF lines.
        text.unicodeScalars
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { scalars -> String in
                var s = String(String.UnicodeScalarView(scalars))
                let hadCR = s.hasSuffix("\r")
                if hadCR { s.removeLast() }
                while s.last == " " { s.removeLast() }
                if hadCR { s.append("\r") }
                return s
            }
            .joined(separator: "\n")
    }

    /// Clamp and strip control bytes from a notification field before forwarding to
    /// UNUserNotificationCenter — the payload comes from terminal output.
    static func sanitizeNotificationText(_ s: String, max: Int) -> String {
        var out = String.UnicodeScalarView()
        out.reserveCapacity(min(s.unicodeScalars.count, max))
        var count = 0
        for scalar in s.unicodeScalars where count < max {
            let v = scalar.value
            if v < 0x20 && v != 0x0A { continue }              // strip C0 except newline
            if v >= 0x80 && v <= 0x9F { continue }             // strip 8-bit C1
            out.append(scalar)
            count += 1
        }
        return String(out)
    }

    /// Parse an OSC 777 payload (minus the "777;" prefix) into (title, body).
    /// Format: `notify;<title>;<body>`. Returns nil for malformed payloads.
    static func parseOSC777(_ text: String) -> (title: String, body: String)? {
        let parts = text.split(separator: ";", maxSplits: 2,
                               omittingEmptySubsequences: false).map(String.init)
        guard parts.first == "notify", parts.count >= 2 else { return nil }
        return (title: parts[1], body: parts.count >= 3 ? parts[2] : "")
    }

    /// Parse an OSC 133 FinalTerm shell-integration payload.
    /// A = prompt start, B = command start, C = command executed, D;<exit> = finished.
    enum OSC133Event: Equatable {
        case promptStart
        case commandStart
        case commandFinished(exitCode: Int?)
    }

    static func parseOSC133(_ text: String) -> OSC133Event? {
        guard let first = text.first else { return nil }
        switch first {
        case "A": return .promptStart
        case "B": return .commandStart
        case "D":
            let parts = text.split(separator: ";", maxSplits: 1)
            let exit = parts.count > 1 ? Int(parts[1]) : nil
            return .commandFinished(exitCode: exit)
        default: return nil
        }
    }

    override func bell(source: Terminal) {
        super.bell(source: source)
        Task { @MainActor [weak self] in
            self?.onBell?()
        }
    }

    /// Open a link resolved from an OSC 8 payload or from implicit link detection.
    /// SwiftTerm's default only handles URLs with a scheme — plain file paths like
    /// `Mosaic/App/AppDelegate.swift` or `src/foo.rs:42:10` fall through and error
    /// out. We resolve them against the terminal's cwd and open the file.
    public func requestOpenLink(source _: TerminalView, link: String, params _: [String: String]) {
        let url = Self.resolveOpenableURL(
            for: link,
            cwd: enclosingTerminalWindowView?.currentCwd ?? FileManager.default.homeDirectoryForCurrentUser.path)
        if let url { NSWorkspace.shared.open(url) }
    }

    /// Schemes that are categorically dangerous from untrusted terminal output
    /// and we refuse to hand to NSWorkspace. Everything else is allowed —
    /// users legitimately click `vscode://`, `slack://`, `zoom://`, custom
    /// editor schemes, etc. and we don't want to break that workflow.
    /// `file://` is handled separately (path-containment check below).
    static let deniedLinkSchemes: Set<String> = ["javascript", "data", "vbscript"]

    /// Pure function so we can unit-test without an NSWorkspace side effect.
    static func resolveOpenableURL(for link: String, cwd: String) -> URL? {
        // Reject pathologically long inputs before any regex / canonicalisation
        // work — both inputs are PTY-controlled and unbounded.
        guard link.utf8.count <= 4096, cwd.utf8.count <= 4096 else { return nil }
        let trimmed = link.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        // Classify as URL vs. filesystem path. URL(string:) parses "hello.txt:42"
        // as scheme="hello.txt" because the scheme grammar allows dots; gate on
        // an explicit "://" so compiler-output paths aren't mis-classified.
        // Opaque schemes like `mailto:` are accepted in the second branch.
        var pathBody = trimmed
        if trimmed.contains("://"), let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased() {
            if scheme == "file" {
                // Unwrap to the underlying path and fall through so the same
                // canonicalise + containment check applies.
                pathBody = url.path
            } else if deniedLinkSchemes.contains(scheme) {
                return nil
            } else {
                return url
            }
        } else if let colon = trimmed.firstIndex(of: ":"),
                  let url = URL(string: trimmed),
                  let scheme = url.scheme?.lowercased(),
                  // Avoid mis-classifying "hello.txt:42" — scheme must look like
                  // a real scheme (letters only, no dots) for the opaque branch.
                  trimmed[..<colon].allSatisfy({ $0.isLetter }),
                  !deniedLinkSchemes.contains(scheme) {
            return url
        }

        // Strip trailing `:line` or `:line:col` suffix (compiler output).
        let path = pathBody.replacingOccurrences(
            of: #":[0-9]+(?::[0-9]+)?$"#,
            with: "",
            options: .regularExpression)

        // Expand ~ and resolve against cwd for relative paths.
        let expanded = (path as NSString).expandingTildeInPath
        let joined = expanded.hasPrefix("/")
            ? expanded
            : (cwd as NSString).appendingPathComponent(expanded)

        // Canonicalise to fold out `..` segments and symlinks before exists-check.
        let resolved = URL(fileURLWithPath: joined)
            .resolvingSymlinksInPath().standardizedFileURL.path
        var isDir: ObjCBool = false
        guard FileManager.default.fileExists(atPath: resolved, isDirectory: &isDir) else { return nil }
        return URL(fileURLWithPath: resolved, isDirectory: isDir.boolValue)
    }

    /// Route find-panel actions to our custom find bar. SwiftTerm's bundled find UI
    /// (added with the GPU backend) hangs the main thread when shown inside our world-
    /// space terminal layout, so we don't call super.
    override func performFindPanelAction(_ sender: Any?) {
        guard let item = sender as? NSMenuItem,
              let host = enclosingTerminalWindowView else { return }
        switch item.tag {
        case Int(NSFindPanelAction.showFindPanel.rawValue):
            host.showFindBar()
        case Int(NSFindPanelAction.next.rawValue):
            host.findNext()
        case Int(NSFindPanelAction.previous.rawValue):
            host.findPrevious()
        default:
            break
        }
    }

    fileprivate var enclosingTerminalWindowView: TerminalWindowView? {
        var view: NSView? = superview
        while let v = view {
            if let tw = v as? TerminalWindowView { return tw }
            view = v.superview
        }
        return nil
    }
}

private let titleBarHeight: CGFloat = 28
private let minSize = CGSize(width: 200, height: 120)

/// A free-floating terminal window in world space.
/// Contains a title bar, a SwiftTerm LocalProcessTerminalView, and 8 resize handles.
final class TerminalWindowView: NSView {

    // MARK: - Identity

    let id = UUID()
    let shell: String
    var currentCwd: String
    var currentTitle: String = "Terminal"

    /// True once the shell has emitted its first title sequence — used to gate
    /// broadcast input so fresh terminals aren't sent keystrokes before the
    /// shell prompt is ready.
    private(set) var shellReady = false

    // MARK: - Callbacks

    var onClose: (() -> Void)?
    var onMoved: (() -> Void)?
    /// Fired when a drag or resize gesture completes; carries (fromFrame, toFrame).
    var onMoveEnded: ((CGRect, CGRect) -> Void)?
    /// Called during drag with the proposed frame; returns the (possibly snapped) frame.
    var snapFrame: ((CGRect, ResizeHandleView.Edge?) -> CGRect)?
    var clearSnapGuides: (() -> Void)?
    /// Raw input bytes to broadcast (only fired if broadcast mode is active upstream).
    var onBroadcastKey: ((Data) -> Void)?
    /// Fired each drag tick with the world-space delta; used for group-move.
    var onDragDelta: ((CGFloat, CGFloat) -> Void)?
    /// Fired when a title-bar drag gesture begins; used for group-move undo capture.
    var onDragBegan: (() -> Void)?
    var onBell: (() -> Void)?
    /// (title, body) from OSC 9 / OSC 777.
    var onNotification: ((String, String) -> Void)?

    /// Active theme — applied 0.8 s after process start (after shell init sequences).
    var theme: Theme = .dark

    // MARK: - Subviews

    private let titleBar = TitleBarView()
    // nonisolated(unsafe): startProcess is dispatched to a background queue to keep
    // forkpty() off the main thread. SwiftTerm dispatches all post-fork UI callbacks
    // back to the main thread internally.
    private nonisolated(unsafe) var termView: InterceptingTerminalView!
    private var findBar: TerminalFindBar?
    private var frameBeforeDrag: CGRect = .zero
    // Shared event monitors — installed once, dispatch to the active terminal.
    private static var sharedMonitorsInstalled = false

    // MARK: - Canvas reference (for zoom-corrected drag)

    weak var canvasView: CanvasView?

    /// Plain-text scrollback to re-display on launch (dimmed, before shell prompt).
    var restoredScrollback: String?

    // MARK: - Init

    init(frame: CGRect, shell: String, cwd: String?) {
        self.shell = shell
        self.currentCwd = cwd ?? FileManager.default.homeDirectoryForCurrentUser.path
        super.init(frame: frame)
        setup()
    }

    required init?(coder: NSCoder) { fatalError() }

    /// Find the TerminalWindowView that owns the current first responder, if any.
    private static func activeTerminalWindow(for event: NSEvent) -> (TerminalWindowView, InterceptingTerminalView)? {
        guard let firstResponder = event.window?.firstResponder as? NSView else { return nil }
        // Walk up the view hierarchy to find our InterceptingTerminalView and its parent.
        var view: NSView? = firstResponder
        while let v = view {
            if let tv = v as? InterceptingTerminalView,
               let tw = tv.enclosingTerminalWindowView {
                return (tw, tv)
            }
            view = v.superview
        }
        return nil
    }

    /// Install shared event monitors once. Each monitor finds the active terminal
    /// via the first responder — O(1) per event regardless of terminal count.
    private static func installSharedMonitors() {
        guard !sharedMonitorsInstalled else { return }
        sharedMonitorsInstalled = true

        // Fix SwiftTerm/macOS interaction: macOS always sets .numericPad on cursor arrow
        // keys. In kitty keyboard mode SwiftTerm uses that flag to distinguish keypad
        // arrows from cursor arrows — causing cursor arrows to be sent as CSI 57419u/57420u
        // (keypad) instead of CSI A/B (cursor). Strip .numericPad so SwiftTerm takes the
        // cursor-arrow path. We can't override keyDown (not open), so we use a local monitor.
        //
        // TODO(2026-04-08): Re-evaluate whether this is still needed. Introduced as a
        // workaround for a Claude Code v2.1.83 regression ("Fixed mouse tracking escape
        // sequences leaking to shell prompt after exit") that caused kitty keyboard mode
        // to be pushed to terminals not in the kitty allow-list. If CC has been fixed,
        // remove this monitor.
        NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            guard let (_, tv) = activeTerminalWindow(for: event) else { return event }

            // Shift+Enter: send \x1b[13;2u (kitty keyboard protocol Shift+Enter).
            if event.keyCode == 36, event.modifierFlags.contains(.shift) {
                tv.send(data: [0x1B, 0x5B, 0x31, 0x33, 0x3B, 0x32, 0x75][...])
                return nil
            }

            // numericPad fix: only applies when kitty keyboard mode is active.
            guard !tv.terminal.keyboardEnhancementFlags.isEmpty,
                  event.modifierFlags.contains(.numericPad),
                  let cgOrig = event.cgEvent,
                  let cgCopy = cgOrig.copy() else { return event }
            cgCopy.flags = cgCopy.flags.subtracting(.maskNumericPad)
            return NSEvent(cgEvent: cgCopy) ?? event
        }

        // Link hover: show pointing-hand cursor automatically over OSC 8 hyperlinks
        // (matches Ghostty/web-browser convention). SwiftTerm sets I-beam in its own
        // mouseMoved; we dispatch async so our cursor set runs AFTER SwiftTerm's.
        NSEvent.addLocalMonitorForEvents(matching: [.mouseMoved, .flagsChanged]) { event in
            guard let (_, tv) = activeTerminalWindow(for: event) else {
                if sharedLinkCursorActive {
                    sharedLinkCursorActive = false
                    DispatchQueue.main.async { NSCursor.iBeam.set() }
                }
                lastLinkHitKey = nil
                lastLinkHit = nil
                return event
            }
            let windowPoint: NSPoint
            if event.type == .mouseMoved {
                windowPoint = event.locationInWindow
            } else if let win = event.window {
                windowPoint = win.mouseLocationOutsideOfEventStream
            } else {
                return event
            }
            let local = tv.convert(windowPoint, from: nil)
            let tvKey = ObjectIdentifier(tv)
            guard let cell = cellAt(local: local, termView: tv) else {
                if sharedLinkCursorActive {
                    sharedLinkCursorActive = false
                    DispatchQueue.main.async { NSCursor.iBeam.set() }
                }
                lastLinkHitKey = nil
                lastLinkHit = nil
                return event
            }
            // Skip the link lookup only when the cell AND the terminal still match.
            if lastLinkHitKey == tvKey, let last = lastLinkHit, last == cell { return event }
            lastLinkHitKey = tvKey
            lastLinkHit = cell
            let overLink = tv.getTerminal().link(
                at: .screen(Position(col: cell.col, row: cell.row)),
                mode: .explicitAndImplicit) != nil
            guard overLink != sharedLinkCursorActive else { return event }
            sharedLinkCursorActive = overLink
            // Set cursor AFTER SwiftTerm's mouseMoved delivers I-beam.
            DispatchQueue.main.async {
                (overLink ? NSCursor.pointingHand : NSCursor.iBeam).set()
            }
            return event
        }

    }

    private static func cellAt(local: NSPoint, termView: InterceptingTerminalView) -> (col: Int, row: Int)? {
        let bounds = termView.bounds
        guard bounds.contains(local) else { return nil }
        let terminal = termView.getTerminal()
        let cols = terminal.cols, rows = terminal.rows
        guard cols > 0, rows > 0 else { return nil }
        let cellW = bounds.width / CGFloat(cols)
        let cellH = bounds.height / CGFloat(rows)
        guard cellW > 0, cellH > 0 else { return nil }
        let col = min(max(0, Int(local.x / cellW)), cols - 1)
        // termView is NOT flipped — y=0 is bottom. Terminal row 0 is top.
        let row = min(max(0, Int((bounds.height - local.y) / cellH)), rows - 1)
        return (col, row)
    }

    private static var sharedLinkCursorActive = false
    /// Per-terminal so a cached cell index from a previously-focused terminal
    /// (with different grid dims) can't early-return for an unrelated cell.
    private static var lastLinkHitKey: ObjectIdentifier?
    private static var lastLinkHit: (col: Int, row: Int)?

    // MARK: - Focus state

    var isActive: Bool = false {
        didSet { updateBorder() }
    }
    var isBroadcast: Bool = false

    /// Flash the border a highlight color, pulsing twice before restoring.
    func flashBorder(color: NSColor = .systemGreen) {
        guard let layer else { return }
        let original = layer.borderColor
        let highlight = color.cgColor
        let flash = CAKeyframeAnimation(keyPath: "borderColor")
        flash.values = [original as Any, highlight, original as Any, highlight, original as Any]
        flash.keyTimes = [0, 0.15, 0.5, 0.65, 1]
        flash.duration = 1.6
        flash.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)
        layer.add(flash, forKey: "bellFlash")
    }

    private func updateBorder() {
        let dark = theme.terminalBackground.isPerceivedDark
        layer?.borderColor = isActive
            ? (dark ? NSColor(white: 0.75, alpha: 1) : NSColor(white: 0.2, alpha: 1)).cgColor
            : (dark ? NSColor(white: 0.25, alpha: 1) : NSColor(white: 0.72, alpha: 1)).cgColor
        layer?.borderWidth = isActive ? 2 : 1
    }

    private func setup() {
        wantsLayer = true
        layer?.cornerRadius = 8
        layer?.masksToBounds = true
        layer?.borderColor = NSColor(white: 0.25, alpha: 1).cgColor
        layer?.borderWidth = 1
        layer?.backgroundColor = Theme.dark.terminalBackground.cgColor

        setupTitleBar()
        setupTerminal()
        setupResizeHandles()
    }

    // MARK: - Title bar

    private func setupTitleBar() {
        titleBar.translatesAutoresizingMaskIntoConstraints = false
        addSubview(titleBar)
        NSLayoutConstraint.activate([
            titleBar.leadingAnchor.constraint(equalTo: leadingAnchor),
            titleBar.trailingAnchor.constraint(equalTo: trailingAnchor),
            titleBar.topAnchor.constraint(equalTo: topAnchor),
            titleBar.heightAnchor.constraint(equalToConstant: titleBarHeight),
        ])

        titleBar.onClose = { [weak self] in self?.onClose?() }

        titleBar.onDragBegan = { [weak self] in
            guard let self else { return }
            frameBeforeDrag = frame
            onDragBegan?()
        }

        titleBar.onDrag = { [weak self] screenDX, screenDY in
            guard let self, let cv = self.canvasView else { return }
            let zoom = cv.currentZoom
            let proposed = CGRect(x: self.frame.origin.x + screenDX / zoom,
                                  y: self.frame.origin.y - screenDY / zoom,
                                  width: self.frame.width, height: self.frame.height)
            let oldOrigin = self.frame.origin
            self.frame = self.snapFrame?(proposed, nil) ?? proposed
            self.onDragDelta?(self.frame.origin.x - oldOrigin.x, self.frame.origin.y - oldOrigin.y)
            self.onMoved?()
        }

        titleBar.onDragEnded = { [weak self] in
            guard let self else { return }
            clearSnapGuides?()
            guard frame != frameBeforeDrag else { return }
            onMoveEnded?(frameBeforeDrag, frame)
        }
    }

    // MARK: - Terminal

    private func setupTerminal() {
        // Frame will be updated in layoutSubviews
        let termFrame = CGRect(x: 0, y: titleBarHeight,
                               width: frame.width, height: frame.height - titleBarHeight)
        termView = InterceptingTerminalView(frame: termFrame)
        termView.translatesAutoresizingMaskIntoConstraints = false
        termView.processDelegate = self
        termView.onSendData = { @Sendable [weak self] data in
            let bytes = Data(data)
            Task { @MainActor [weak self] in
                self?.onBroadcastKey?(bytes)
            }
        }
        termView.onBell = { [weak self] in self?.onBell?() }
        termView.nativeForegroundColor = theme.terminalForeground
        termView.nativeBackgroundColor = theme.terminalBackground
        addSubview(termView)

        let p: CGFloat = 8
        NSLayoutConstraint.activate([
            termView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: p),
            termView.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -p),
            termView.topAnchor.constraint(equalTo: topAnchor, constant: titleBarHeight),
            termView.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -p),
        ])

        // Force dark appearance so the legacy scroller track renders dark
        // regardless of the system-wide appearance setting.
        termView.appearance = NSAppearance(named: .darkAqua)

        registerOSCHandlers()
        Self.installSharedMonitors()
        startRedrawWatchdog()

        startProcess()
    }

    // MARK: - OSC handlers

    private func registerOSCHandlers() {
        let terminal = termView.getTerminal()

        // OSC 9 — NOT overridden. SwiftTerm handles OSC 9;4 (progress bar) natively
        // and oscProgressReport is internal. Plain OSC 9 notifications are rare;
        // Claude Code uses BEL and OSC 777 instead.

        // OSC 777 — notify;title;body
        // SwiftTerm parses this but the delegate is a protocol extension no-op.
        // Override via parser handler. Cap payload size and sanitize control bytes
        // (terminal output is untrusted; an unbounded OSC payload would allocate
        // a huge String on MainActor and forward it to UNUserNotificationCenter).
        terminal.parser.oscHandlers[777] = { [weak self] data in
            guard data.count <= 8192 else { return }
            let text = String(bytes: data, encoding: .utf8) ?? ""
            guard let parsed = InterceptingTerminalView.parseOSC777(text) else { return }
            let title = InterceptingTerminalView.sanitizeNotificationText(parsed.title, max: 128)
            let body  = InterceptingTerminalView.sanitizeNotificationText(parsed.body,  max: 512)
            Task { @MainActor [weak self] in
                self?.onNotification?(title, body)
            }
        }

        // OSC 133 D — command finished. Only wire this marker; busy indicators
        // on B/C are a bad idea for TUIs (claude/vim) which never emit D until exit,
        // leaving the whole app pulsing.
        terminal.parser.oscHandlers[133] = { [weak self] data in
            guard data.count <= 8192 else { return }
            let text = String(bytes: data, encoding: .utf8) ?? ""
            guard case .commandFinished(let exit) = InterceptingTerminalView.parseOSC133(text) else { return }
            Task { @MainActor [weak self] in
                self?.titleBar.setStatus(.finished(exitCode: exit))
            }
        }
    }

    /// Bound restored scrollback so a single pathological line (e.g.
    /// `cat /dev/urandom | base64 -w0`) can't bloat workspace.json or stall the
    /// next launch when re-fed to the terminal.
    static let maxScrollbackLineChars = 4096
    static let maxScrollbackTotalChars = 256 * 1024

    /// Extract up to `maxLines` of scrollback + visible screen content as plain text.
    func extractScrollbackText(maxLines: Int = 300) -> String {
        guard let t = termView.terminal else { return "" }
        let cap = Self.maxScrollbackLineChars
        let render: (Int) -> String? = { row in
            guard let line = t.getScrollInvariantLine(row: row) else { return nil }
            let s = line.translateToString(trimRight: true,
                                           characterProvider: { let c = $0.getCharacter(); return c == "\0" ? " " : c })
            return s.count > cap ? String(s.prefix(cap)) : s
        }

        var lines: [String] = []

        // Walk backwards through scrollback (negative row indices into getScrollInvariantLine)
        var row = -1
        while lines.count < maxLines, let s = render(row) {
            lines.insert(s, at: 0)
            row -= 1
        }

        // Visible screen lines
        for r in 0..<t.rows {
            if let s = render(r) { lines.append(s) }
        }

        // Drop trailing blank lines
        while lines.last?.isEmpty == true { lines.removeLast() }
        let joined = lines.joined(separator: "\r\n")
        return joined.count > Self.maxScrollbackTotalChars
            ? String(joined.suffix(Self.maxScrollbackTotalChars))
            : joined
    }

    // MARK: - Find

    private var matchTotal: Int = 0
    private var matchIndex: Int = 0  // 1-based; 0 means no current match

    func showFindBar() {
        let bar = ensureFindBar()
        if bar.searchText.isEmpty,
           let selected = termView.getSelection(),
           !selected.isEmpty,
           !selected.contains("\n") {
            bar.searchText = selected
            recomputeMatchTotal(term: selected)
            if matchTotal > 0 {
                matchIndex = 1
                _ = termView.findNext(selected)
            }
        }
        bar.setMatchInfo(current: matchIndex, total: matchTotal)
        bar.isHidden = false
        bar.focus()
    }

    func hideFindBar() {
        findBar?.isHidden = true
        termView.clearSearch()
        matchTotal = 0
        matchIndex = 0
        window?.makeFirstResponder(termView)
    }

    func findNext() {
        guard let bar = findBar, !bar.searchText.isEmpty else {
            showFindBar()
            return
        }
        // Recompute on every action — scrollback grows under streaming output, and
        // our counter would otherwise drift away from SwiftTerm's internal cursor.
        recomputeMatchTotal(term: bar.searchText)
        guard matchTotal > 0 else {
            matchIndex = 0
            bar.setMatchInfo(current: 0, total: 0)
            return
        }
        matchIndex = matchIndex >= matchTotal ? 1 : matchIndex + 1
        _ = termView.findNext(bar.searchText)
        bar.setMatchInfo(current: matchIndex, total: matchTotal)
    }

    func findPrevious() {
        guard let bar = findBar, !bar.searchText.isEmpty else {
            showFindBar()
            return
        }
        recomputeMatchTotal(term: bar.searchText)
        guard matchTotal > 0 else {
            matchIndex = 0
            bar.setMatchInfo(current: 0, total: 0)
            return
        }
        matchIndex = matchIndex <= 1 ? matchTotal : matchIndex - 1
        _ = termView.findPrevious(bar.searchText)
        bar.setMatchInfo(current: matchIndex, total: matchTotal)
    }

    private func ensureFindBar() -> TerminalFindBar {
        if let bar = findBar { return bar }
        let bar = TerminalFindBar()
        bar.translatesAutoresizingMaskIntoConstraints = false
        bar.isHidden = true
        bar.onSearchChanged = { [weak self] term in
            guard let self else { return }
            if term.isEmpty {
                self.termView.clearSearch()
                self.matchTotal = 0
                self.matchIndex = 0
            } else {
                self.recomputeMatchTotal(term: term)
                if self.matchTotal > 0 {
                    self.matchIndex = 1
                    _ = self.termView.findNext(term)
                } else {
                    self.matchIndex = 0
                    self.termView.clearSearch()
                }
            }
            self.findBar?.setMatchInfo(current: self.matchIndex, total: self.matchTotal)
        }
        bar.onFindNext = { [weak self] in self?.findNext() }
        bar.onFindPrevious = { [weak self] in self?.findPrevious() }
        bar.onClose = { [weak self] in self?.hideFindBar() }
        addSubview(bar)
        NSLayoutConstraint.activate([
            bar.topAnchor.constraint(equalTo: topAnchor, constant: titleBarHeight + 4),
            bar.trailingAnchor.constraint(equalTo: trailingAnchor, constant: -6),
            bar.leadingAnchor.constraint(greaterThanOrEqualTo: leadingAnchor, constant: 6),
            bar.widthAnchor.constraint(lessThanOrEqualToConstant: 420)
        ])
        findBar = bar
        return bar
    }

    /// Count case-insensitive substring occurrences across the entire scrollback +
    /// visible buffer. SwiftTerm's full-buffer match count is internal, so we walk
    /// rows via the public getScrollInvariantLine and tally matches per line.
    private func recomputeMatchTotal(term: String) {
        guard !term.isEmpty, let terminal = termView.terminal else {
            matchTotal = 0
            return
        }
        // getScrollInvariantLine's valid row range is contiguous starting at
        // some non-negative `linesTop`. Find it with a doubling probe + binary
        // search, then walk forward until the function returns nil again.
        let firstRow: Int
        if terminal.getScrollInvariantLine(row: 0) != nil {
            firstRow = 0
        } else {
            var hi = 1
            while terminal.getScrollInvariantLine(row: hi) == nil {
                if hi > 1 << 24 { matchTotal = 0; return }
                hi <<= 1
            }
            var lo = hi >> 1
            while lo < hi {
                let mid = (lo + hi) >> 1
                if terminal.getScrollInvariantLine(row: mid) == nil {
                    lo = mid + 1
                } else {
                    hi = mid
                }
            }
            firstRow = lo
        }

        var count = 0
        var bytesScanned = 0
        var row = firstRow
        let lower = term.lowercased()
        let perRowCap = Self.maxScrollbackLineChars
        let totalCap = 16 * 1024 * 1024
        while let line = terminal.getScrollInvariantLine(row: row) {
            var s = line.translateToString(
                trimRight: true,
                characterProvider: { let c = $0.getCharacter(); return c == "\0" ? " " : c }
            ).lowercased()
            if s.count > perRowCap { s = String(s.prefix(perRowCap)) }
            bytesScanned += s.utf8.count
            if !s.isEmpty {
                var idx = s.startIndex
                while let r = s.range(of: lower, range: idx..<s.endIndex) {
                    count += 1
                    idx = r.upperBound
                }
            }
            row += 1
            if row - firstRow > 200_000 || bytesScanned > totalCap { break }
        }
        matchTotal = count
    }

    /// Clear scrollback and screen (Cmd+K behaviour). Feeds ESC sequences directly
    /// to the terminal display — does not send anything to the PTY.
    func clearScrollback() {
        // ESC[H  = cursor home
        // ESC[2J = erase screen
        // ESC[3J = erase saved lines (scrollback)
        termView.feed(byteArray: [0x1B, 0x5B, 0x48,
                                  0x1B, 0x5B, 0x32, 0x4A,
                                  0x1B, 0x5B, 0x33, 0x4A])
    }

    private func startProcess() {
        let settings = TerminalSettings.shared
        applyTerminalSettings(settings)

        var env = ProcessInfo.processInfo.environment
        env["TERM"] = "xterm-256color"
        env["COLORTERM"] = "truecolor"

        var isDir: ObjCBool = false
        let cwdExists = FileManager.default.fileExists(atPath: currentCwd, isDirectory: &isDir) && isDir.boolValue
        let cwd = cwdExists ? currentCwd : FileManager.default.homeDirectoryForCurrentUser.path

        let execName = "-" + (shell as NSString).lastPathComponent
        let envList  = env.map { "\($0.key)=\($0.value)" }
        let shellPath = shell
        let scrollbackLines = settings.scrollbackLines
        let cursorStyle = settings.swiftTermCursorStyle

        // Cache window size before background dispatch — startProcess calls getWindowSize()
        // which reads self.frame; that must happen on the main thread.
        termView!.cachedWindowSize = termView!.getWindowSize()

        // Run forkpty on a background thread so the ~2 s atfork-handler cost
        // (libBacktraceRecording) doesn't block the main thread and cause a beachball.
        // SwiftTerm annotates startProcess as @MainActor but the underlying forkpty
        // call is thread-safe; the annotation is overly conservative. Calling from a
        // background thread here is intentional and safe.
        DispatchQueue.global(qos: .userInitiated).async { [termView] in
            termView!.startProcess(
                executable: shellPath,
                args: [],
                environment: envList,
                execName: execName,
                currentDirectory: cwd
            )
            DispatchQueue.main.async {
                // Clear the cached size now that the process is running.
                // sizeChanged() calls getWindowSize() to build the TIOCSWINSZ winsize;
                // from this point it must read the live frame, not the startup snapshot.
                termView!.cachedWindowSize = nil
                termView!.changeScrollback(scrollbackLines)
                termView!.getTerminal().setCursorStyle(cursorStyle)
            }
        }

        // Apply theme and optionally restore scrollback after shell init sequences have run.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { [weak self] in
            guard let self else { return }
            self.applyTheme(self.theme)
            if let raw = self.restoredScrollback, !raw.isEmpty {
                self.restoredScrollback = nil
                // Cap restored bytes — workspace.json is untrusted on disk.
                let text = raw.count > Self.maxScrollbackTotalChars
                    ? String(raw.suffix(Self.maxScrollbackTotalChars))
                    : raw
                // Strip all ANSI/OSC escape sequences (incl. 8-bit C1) from the
                // persisted scrollback before re-feeding it. Without this, a tampered
                // workspace.json could inject OSC sequences (OSC 8 hyperlinks, OSC 1337
                // file transfers, title spoofing) into the running terminal.
                // NUL bytes (U+0000) arise from terminal cells never explicitly written
                // (cursor-positioned TUI layouts). Replace them with spaces.
                let safe = TerminalWindowView.stripEscapeSequences(text)
                    .replacingOccurrences(of: "\u{0000}", with: " ")
                // Dim color + italic, then show saved content, then reset
                let dimmed = "\u{1B}[2;3m" + safe + "\u{1B}[0m\r\n"
                self.termView.feed(text: dimmed)
            }
        }
    }

    /// Remove ANSI CSI sequences (`ESC [ … m/A/B/…`), OSC sequences
    /// (`ESC ] … BEL/ST`), and bare `ESC X` two-character sequences from `text`.
    /// Also handles the 8-bit C1 single-byte equivalents (0x9B CSI, 0x9D OSC,
    /// 0x90 DCS, 0x9E PM, 0x9F APC, 0x98 SOS) which xterm-class parsers (including
    /// SwiftTerm) honour and which UTF-8-encode to U+0080–U+009F (two bytes
    /// 0xC2 0x9X). A tampered workspace.json scrollback containing raw 0x9D…BEL
    /// would otherwise inject an OSC sequence when re-fed at launch.
    static func stripEscapeSequences(_ text: String) -> String {
        var result = ""
        result.reserveCapacity(text.count)
        var iter = text.unicodeScalars.makeIterator()
        while let ch = iter.next() {
            // 7-bit ESC-introduced or 8-bit C1 single-byte introducer.
            if ch == "\u{1B}" {
                guard let next = iter.next() else { break }
                consumeEscapeBody(intro: next, iter: &iter)
            } else if (0x80...0x9F).contains(ch.value) {
                // Map C1 to its 7-bit equivalent introducer and consume.
                let mapped: Unicode.Scalar
                switch ch.value {
                case 0x9B: mapped = "["
                case 0x9D: mapped = "]"
                case 0x90: mapped = "P"
                case 0x9E: mapped = "^"
                case 0x9F: mapped = "_"
                case 0x98: mapped = "X"
                default:
                    // Other C1 controls — just drop the single byte.
                    continue
                }
                consumeEscapeBody(intro: mapped, iter: &iter)
            } else {
                result.unicodeScalars.append(ch)
            }
        }
        return result
    }

    /// Consume the body of an escape sequence given its post-introducer class byte.
    /// Mutating because the iterator is advanced.
    private static func consumeEscapeBody(intro: Unicode.Scalar,
                                          iter: inout String.UnicodeScalarView.Iterator) {
        switch intro {
        case "[":
            // CSI: consume until a final byte in 0x40–0x7E.
            while let c = iter.next() {
                if c.value >= 0x40 && c.value <= 0x7E { break }
            }
        case "]", "P", "X", "^", "_":
            // ST-terminated: consume until BEL, ESC \, or 8-bit ST (U+009C).
            var prev: Unicode.Scalar = "\u{00}"
            while let c = iter.next() {
                if c == "\u{07}" || c == "\u{9C}" { break }
                if prev == "\u{1B}" && c == "\\" { break }
                prev = c
            }
        default:
            break       // Two-character escape; introducer already consumed.
        }
    }

    func applyTerminalSettings(_ settings: TerminalSettings) {
        termView.optionAsMetaKey        = settings.optionAsMetaKey
        termView.backspaceSendsControlH = settings.backspaceSendsControlH
        termView.allowMouseReporting    = settings.allowMouseReporting
        termView.useBrightColors        = settings.useBrightColors
        termView.changeScrollback(settings.scrollbackLines)
        termView.getTerminal().setCursorStyle(settings.swiftTermCursorStyle)
    }

    func applyTheme(_ theme: Theme) {
        self.theme = theme
        termView.nativeForegroundColor = theme.terminalForeground
        termView.nativeBackgroundColor = theme.terminalBackground
        termView.font = theme.terminalFont
        termView.feed(text: theme.oscSequences)
        layer?.backgroundColor = theme.terminalBackground.cgColor
        // syncTitleBarColor preserves the broadcast tint when active; calling
        // titleBar.applyTheme directly would clobber it.
        syncTitleBarColor()
        updateBorder()
    }

    private func syncTitleBarColor() {
        if isBroadcast {
            titleBar.layer?.backgroundColor = NSColor(red: 0.15, green: 0.3, blue: 0.15, alpha: 1).cgColor
        } else {
            titleBar.applyTheme(background: theme.terminalBackground, foreground: theme.terminalForeground)
        }
    }

    // MARK: - Resize handles

    private func setupResizeHandles() {
        for edge in ResizeHandleView.Edge.allCases {
            let h = ResizeHandleView(edge: edge)
            h.translatesAutoresizingMaskIntoConstraints = false
            addSubview(h)
            h.installConstraints(in: self)
            h.onResizeBegan = { [weak self] in
                guard let self else { return }
                frameBeforeDrag = frame
            }
            h.onResize = { [weak self] dx, dy in
                self?.handleResize(edge: edge, screenDX: dx, screenDY: dy)
            }
            h.onResizeEnded = { [weak self] in
                guard let self else { return }
                clearSnapGuides?()
                guard frame != frameBeforeDrag else { return }
                onMoveEnded?(frameBeforeDrag, frame)
            }
        }
    }

    private func handleResize(edge: ResizeHandleView.Edge, screenDX: CGFloat, screenDY: CGFloat) {
        guard let cv = canvasView else { return }
        let zoom = cv.currentZoom
        let dx = screenDX / zoom
        // screenDY is window-space y-up; world space is y-down, so negate
        let dy = -screenDY / zoom

        var r = frame
        switch edge {
        case .topLeft:
            r.origin.x += dx; r.size.width -= dx
            r.origin.y += dy; r.size.height -= dy
        case .top:
            r.origin.y += dy; r.size.height -= dy
        case .topRight:
            r.size.width += dx
            r.origin.y += dy; r.size.height -= dy
        case .left:
            r.origin.x += dx; r.size.width -= dx
        case .right:
            r.size.width += dx
        case .bottomLeft:
            r.origin.x += dx; r.size.width -= dx
            r.size.height += dy
        case .bottom:
            r.size.height += dy
        case .bottomRight:
            r.size.width += dx
            r.size.height += dy
        }

        r.size.width  = max(r.size.width,  minSize.width)
        r.size.height = max(r.size.height, minSize.height)

        // Apply edge-aware snapping: call snapFrame to find alignment deltas, then
        // apply each delta to the dimension that's actually moving for this edge.
        if let snap = snapFrame {
            let snapped = snap(r, edge)
            let sdx = snapped.origin.x - r.origin.x
            let sdy = snapped.origin.y - r.origin.y

            let dragsRight  = edge == .right  || edge == .topRight    || edge == .bottomRight
            let dragsLeft   = edge == .left   || edge == .topLeft     || edge == .bottomLeft
            let dragsBottom = edge == .bottom || edge == .bottomLeft  || edge == .bottomRight
            let dragsTop    = edge == .top    || edge == .topLeft     || edge == .topRight

            if dragsRight       { r.size.width  += sdx }
            else if dragsLeft   { r.origin.x    += sdx; r.size.width  -= sdx }
            if dragsBottom      { r.size.height += sdy }
            else if dragsTop    { r.origin.y    += sdy; r.size.height -= sdy }

            r.size.width  = max(r.size.width,  minSize.width)
            r.size.height = max(r.size.height, minSize.height)
        }

        frame = r
        onMoved?()
    }

    // MARK: - Focus

    func focusTerminal() {
        window?.makeFirstResponder(termView)
    }

    // SwiftTerm's pendingDisplay throttle races between background feeds and
    // main-thread resets; long-running apps occasionally see it stick `true`,
    // freezing the view until a scroll forces setNeedsDisplay. Nudge AppKit
    // ourselves whenever the buffer has unrendered updates.
    private var redrawWatchdog: DispatchSourceTimer?

    private func startRedrawWatchdog() {
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + 1, repeating: 1, leeway: .milliseconds(200))
        t.setEventHandler { [weak self] in
            guard let self, self.termView.getTerminal().getUpdateRange() != nil else { return }
            self.termView.needsDisplay = true
        }
        t.resume()
        redrawWatchdog = t
    }

    deinit { redrawWatchdog?.cancel() }

    // MARK: - Input broadcasting

    func sendInput(_ data: Data) {
        let bytes = [UInt8](data)
        termView.suppressBroadcast = true
        termView.send(data: bytes[...])
        termView.suppressBroadcast = false
    }

    // MARK: - Visual state

    func setBroadcastHighlight(_ on: Bool) {
        isBroadcast = on
        syncTitleBarColor()
    }

    func terminate() {
        // SwiftTerm tears down the PTY when the view is deallocated,
        // but we can signal the process to exit cleanly.
        termView.send(data: [0x04][...])  // Ctrl-D / EOF
    }
}

// MARK: - LocalProcessTerminalViewDelegate

extension TerminalWindowView: LocalProcessTerminalViewDelegate {
    nonisolated func sizeChanged(source: LocalProcessTerminalView, newCols: Int, newRows: Int) {
        // SIGWINCH is sent automatically by SwiftTerm; nothing extra needed here
    }

    nonisolated func setTerminalTitle(source: LocalProcessTerminalView, title: String) {
        Task { @MainActor [weak self] in
            self?.shellReady = true
            self?.currentTitle = title
            self?.titleBar.titleLabel.stringValue = title
            self?.syncTitleBarColor()
        }
    }

    nonisolated func hostCurrentDirectoryUpdate(source: TerminalView, directory: String?) {
        guard let dir = directory else { return }
        // SwiftTerm passes a file:// URL; extract the plain POSIX path.
        let path = URL(string: dir)?.path ?? dir
        Task { @MainActor [weak self] in
            self?.currentCwd = path
        }
    }

    nonisolated func processTerminated(source: TerminalView, exitCode: Int32?) {
        Task { @MainActor [weak self] in
            self?.onClose?()
        }
    }
}


