import Testing
@testable import Mosaic

/// Tests for InterceptingTerminalView.shouldBroadcast — the filter that decides
/// whether a byte slice handed back from SwiftTerm's `send` callback is a user
/// keystroke (broadcast to peer terminals) or a terminal protocol response
/// generated by the emulator itself (stay local).
@MainActor
struct BroadcastFilterTests {

    private func slice(_ bytes: [UInt8]) -> ArraySlice<UInt8> { bytes[...] }

    // MARK: - Empty input (regression for paste-of-empty crash)

    @Test func emptySliceDoesNotCrashAndIsNotBroadcast() {
        // SwiftTerm hands us a zero-byte slice on some paste/insertText paths.
        // Subscripting an empty ArraySlice traps — the filter must reject first.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([])) == false)
    }

    // MARK: - User keystrokes (broadcast)

    @Test func plainAsciiKeystrokeBroadcasts() {
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x61])) == true)            // "a"
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x68, 0x69])) == true)      // "hi"
    }

    @Test func enterKeyBroadcasts() {
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x0D])) == true)            // \r
    }

    @Test func cursorArrowBroadcasts() {
        // ESC [ A — cursor up, sent by user pressing arrow key.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5B, 0x41])) == true)
    }

    @Test func bareEscBroadcasts() {
        // Lone ESC (e.g. vim escape) — too short to be a protocol response.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B])) == true)
    }

    @Test func escBracketTwoByteBroadcasts() {
        // ESC [ alone (incomplete CSI) — not a known protocol response prefix.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5B])) == true)
    }

    // MARK: - Protocol responses (stay local)

    @Test func decPrivateResponsesAreFiltered() {
        // ESC [ ? — DA1 / DA2 / DECSET reports.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5B, 0x3F])) == false)
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5B, 0x3F, 0x36, 0x32, 0x3B, 0x63])) == false)
        // ESC [ > — secondary DA / XTWINOPS responses.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5B, 0x3E])) == false)
    }

    @Test func dcsOscPmApcSosFiltered() {
        // ESC P — DCS
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x50, 0x41])) == false)
        // ESC ] — OSC
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5D, 0x30])) == false)
        // ESC X — SOS
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x58, 0x41])) == false)
        // ESC ^ — PM
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5E, 0x41])) == false)
        // ESC _ — APC
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x1B, 0x5F, 0x41])) == false)
    }

    @Test func eightBitC1Filtered() {
        // 8-bit C1 single-byte equivalents of the above.
        for b: UInt8 in 0x90...0x9F {
            #expect(InterceptingTerminalView.shouldBroadcast(slice([b])) == false,
                    "0x\(String(b, radix: 16)) should be filtered")
        }
    }

    @Test func eightBitC1AtStartFiltersWholeSlice() {
        // Even with trailing payload, an 8-bit C1 introducer at byte 0 is filtered.
        #expect(InterceptingTerminalView.shouldBroadcast(slice([0x9D, 0x38, 0x3B, 0x3B])) == false)
    }

    // MARK: - Edge cases

    @Test func nonStartIndexSliceWorks() {
        // ArraySlice keeps the parent array's indices — startIndex isn't 0.
        let parent: [UInt8] = [0xFF, 0xFF, 0x61, 0x62]
        let s = parent[2..<4]   // startIndex == 2
        #expect(InterceptingTerminalView.shouldBroadcast(s) == true)
    }

    @Test func nonStartIndexDecPrivateFiltered() {
        let parent: [UInt8] = [0xFF, 0x1B, 0x5B, 0x3F]
        let s = parent[1..<4]   // startIndex == 1
        #expect(InterceptingTerminalView.shouldBroadcast(s) == false)
    }
}
